### PR TITLE
fix import

### PR DESCRIPTION
**Pull request by Dissolutio**
always missing little things...

### CODE REVIEW

**Review by erikamats — COMMENTED** [review]
Did the casing give you an issue? Or was this done for consistency?

**Review by erikamats — DISMISSED** [review]
Did the casing give you an issue? Or was this done for consistency?

**Comment by Dissolutio** [comment]
It failed to render, because the import location did not match the file name. Filename is capitalized, so import has to match

**Review by erikamats — APPROVED** [review]
I'm going to approve but something to note here is that I don't have the casing issue as you did.  We import the component based on the casing it has and then reference its path as the file is named. We can keep how the approved changes will show, but I did want to note that I was not affected by they way it was before.

**Pull request merged**
